In [2]:
import numpy as np
x = np.array([1,2,3], np.int16) # signed 16 bit integer

In [3]:
print(x)
print(type(x))

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
print(x[0]);
print(x[1]);
print(x[2]);
print(x[-1]); # last element

1
2
3
3


In [6]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int16)
print(x)

[[1 2 3]
 [4 5 6]]


In [8]:
print(x[0, 0]);
print(x[-1, -1]);

1
6


In [12]:
# Slicing
print(x[:, 0]) # column 1
print(x[:, 1]) # column 2
print(x[:, 2]) # column 3
print(x[0, :]) # row 1
print(x[1, :]) # row 2

[1 4]
[2 5]
[3 6]
[1 2 3]
[4 5 6]


In [17]:
# 3-dimensional Ndarray
x = np.array([[[1, 2, 3],[4, 5, 6]],[[0, -1, -2],[-3, -4, -5]]], np.int16)
print(x)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 0 -1 -2]
  [-3 -4 -5]]]


In [21]:
print(x[0, 0, 0])
print(x[-1, -1, -1])
print(x[: ,:, 0]) # prints 1st column
print(x[:, :, 1]) # prints 2nd column

1
-5
[[ 1  4]
 [ 0 -3]]
[[ 2  5]
 [-1 -4]]


# NumPy Ndarray Properties

In [26]:
print(x.shape) # 3-dimensional data structure
print(x.ndim) # number of dimensions
print(x.dtype) # data type of all the individual elements
print(x.size) # 12 elements
print(x.nbytes) # 12*2 = 24 bytes (16 bits = 2 bytes)

(2, 2, 3)
3
int16
12
24


In [27]:
print(x.T) # transpose

[[[ 1  0]
  [ 4 -3]]

 [[ 2 -1]
  [ 5 -4]]

 [[ 3 -2]
  [ 6 -5]]]


# NumPy Constants

In [30]:
print(np.inf) # positive infinity
print(np.NAN) # not a number
print(np.NINF) # negative infinity
print(np.NZERO) # positive zero
print(np.PZERO) # negative zero
print(np.e) # mathematical constant
print(np.euler_gamma)
print(np.pi)

inf
nan
-inf
-0.0
0.0
2.718281828459045
0.5772156649015329
3.141592653589793


# Ones and Zeros

In [33]:
x = np.empty([3, 3], np.uint8) # unsigned 8 bit integer
print(x) # 3x3 matrix with random values

[[ 48 255  90]
 [ 65 188   2]
 [  0   0  48]]


In [37]:
# 1's in diagonal and 0's elsewhere
y = np.eye(5, dtype = np.uint8, k=0) # k decides the position of diagonal
print(y)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [40]:
# Identity matrix
x = np.identity(5, dtype = np.uint8)
print(x)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [42]:
x = np.ones((2, 5, 5), dtype = np.int16)
print(x)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [43]:
x = np.zeros((2, 5, 5), dtype = np.int16)
print(x)

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


In [48]:
# An Ndarray with all elements = 4
x = np.full((3, 3, 3), dtype = np.int16, fill_value = 4)
print(x)

[[[4 4 4]
  [4 4 4]
  [4 4 4]]

 [[4 4 4]
  [4 4 4]
  [4 4 4]]

 [[4 4 4]
  [4 4 4]
  [4 4 4]]]


   # Matrix creation routines

In [50]:
# An array with ones at and below the given diagonal and zeros elsewhere
x = np.tri(5, 5, k=0, dtype = np.uint16) # k decides the position of diagonal
print(x)

[[1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 1]]


In [56]:
x = np.ones((5,5), dtype = np.uint8)
print(x)
y = np.tril(x, k = -1) # lower triangular
print(y)
z = np.triu(x, k = -1) # upper triangular
print(z)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [0 1 1 1 1]
 [0 0 1 1 1]
 [0 0 0 1 1]]


# Generating Ndarrays with Random values

In [62]:
# Single dimension array with random elements (integers)
x = np.random.randint(low = 0, high = 9, size = 10)
print(x)
# Random array of size 2x2
x = np.random.rand(3, 3)
print(x)
x = np.random.rand(2,2,2,2,2)
print(x)

[3 1 6 8 8 6 3 4 8 8]
[[ 0.45077861  0.21873748  0.69434719]
 [ 0.54198292  0.63762532  0.33481276]
 [ 0.24788689  0.46260629  0.12736025]]
[[[[[ 0.89526797  0.90755097]
    [ 0.70374728  0.93365549]]

   [[ 0.53797336  0.91621877]
    [ 0.43715583  0.72205062]]]


  [[[ 0.41262713  0.44696716]
    [ 0.16522338  0.17473343]]

   [[ 0.36023849  0.95184136]
    [ 0.27656488  0.08654361]]]]



 [[[[ 0.57652475  0.85177763]
    [ 0.85737021  0.23093653]]

   [[ 0.8088866   0.69382727]
    [ 0.17663422  0.74221186]]]


  [[[ 0.56674506  0.40397094]
    [ 0.2893048   0.21294813]]

   [[ 0.71702791  0.21540947]
    [ 0.87361464  0.06957232]]]]]


# Array Manipulation Routines

In [67]:
x = np.arange(6)
print(x)
y = x.reshape((3, 2)) # reshaped into 3x2 matrix
print(y)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


In [68]:
x = np.array([[0, 1, 2],[3, 4, 5]], dtype = np.uint8)
print(x)

[[0 1 2]
 [3 4 5]]


In [70]:
y = np.reshape(x,6) # value of x will be kept intact
print(y)

[0 1 2 3 4 5]


In [79]:
y = np.ravel(x) # flattens the matrix
print(y)
y = x.flatten('C') # row order by default
print(y)
y = x.flatten('F') # column order
print(y)
# ravel is faster as it doesn't occupy memory

[0 1 2 3 4 5]
[0 1 2 3 4 5]
[0 3 1 4 2 5]


In [4]:
x = np.array([1, 2, 3], dtype = np.uint8)
y = np.array([4, 5, 6], dtype = np.uint8)
print(x.dtype)
print(x)
print(y)

uint8
[1 2 3]
[4 5 6]


In [91]:
z = np.stack((x, y))
print(z)
z = np.stack((x, y), axis = 0) # stacking along a different axis
print(z)
z = np.stack((x, y), axis = 1)
print(z)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [97]:
z = np.dstack((x, y)) # stack arrays in depth wise sequence
print(z)
print(z.shape)

[[[1 4]
  [2 5]
  [3 6]]]
(1, 3, 2)


In [98]:
z = np.hstack((x, y)) # horizontal stacking
print(z)
print(z.shape)

[1 2 3 4 5 6]
(6,)


In [6]:
z = np.vstack((x, y)) # vertical stacking
print(z)
print(z.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [7]:
x = np.arange(9)
print(x)

[0 1 2 3 4 5 6 7 8]


In [8]:
a, b, c = np.split(x, 3)
print(a, b, c)

[0 1 2] [3 4 5] [6 7 8]


In [11]:
x = np.random.rand(4, 4, 4)
y, z = np.split(x, 2)
print(y, z)

[[[ 0.45056123  0.27328413  0.26155626  0.71535627]
  [ 0.02211023  0.8360523   0.57831298  0.43970943]
  [ 0.51344543  0.11859003  0.71967118  0.76341423]
  [ 0.21691585  0.7806976   0.73034354  0.89090707]]

 [[ 0.49892813  0.17903786  0.37161755  0.24641424]
  [ 0.38941192  0.27865497  0.22848607  0.17224166]
  [ 0.4671229   0.7071495   0.6155286   0.94442969]
  [ 0.62296216  0.37089692  0.81264073  0.21967369]]] [[[ 0.74401234  0.89655379  0.50912923  0.46278616]
  [ 0.59446503  0.07414203  0.10507664  0.85546162]
  [ 0.99174945  0.3686375   0.70621608  0.03773458]
  [ 0.76034494  0.11401412  0.20273432  0.48190107]]

 [[ 0.97572558  0.30203548  0.09087594  0.53261055]
  [ 0.7110977   0.70667494  0.36386561  0.30355158]
  [ 0.38756768  0.15186012  0.83481702  0.18159759]
  [ 0.52875512  0.80053579  0.28009549  0.63520221]]]


In [13]:
y, z = np.dsplit(x, 2) # depth
print(y, z)
y, z = np.hsplit(x, 2) # horizontal split
print(y, z)
y, z = np.vsplit(x, 2) # vertical split
print(y, z)

[[[ 0.45056123  0.27328413]
  [ 0.02211023  0.8360523 ]
  [ 0.51344543  0.11859003]
  [ 0.21691585  0.7806976 ]]

 [[ 0.49892813  0.17903786]
  [ 0.38941192  0.27865497]
  [ 0.4671229   0.7071495 ]
  [ 0.62296216  0.37089692]]

 [[ 0.74401234  0.89655379]
  [ 0.59446503  0.07414203]
  [ 0.99174945  0.3686375 ]
  [ 0.76034494  0.11401412]]

 [[ 0.97572558  0.30203548]
  [ 0.7110977   0.70667494]
  [ 0.38756768  0.15186012]
  [ 0.52875512  0.80053579]]] [[[ 0.26155626  0.71535627]
  [ 0.57831298  0.43970943]
  [ 0.71967118  0.76341423]
  [ 0.73034354  0.89090707]]

 [[ 0.37161755  0.24641424]
  [ 0.22848607  0.17224166]
  [ 0.6155286   0.94442969]
  [ 0.81264073  0.21967369]]

 [[ 0.50912923  0.46278616]
  [ 0.10507664  0.85546162]
  [ 0.70621608  0.03773458]
  [ 0.20273432  0.48190107]]

 [[ 0.09087594  0.53261055]
  [ 0.36386561  0.30355158]
  [ 0.83481702  0.18159759]
  [ 0.28009549  0.63520221]]]
[[[ 0.45056123  0.27328413  0.26155626  0.71535627]
  [ 0.02211023  0.8360523   0.578312

In [15]:
x = np.arange(16).reshape(4, 4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [21]:
y = np.flip(x, axis = -1)
print(y)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [20]:
y = np.flip(x, axis = 0)
print(y)

[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [18]:
y = np.flip(x, axis = 1)
print(y)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [22]:
y = np.fliplr(x) # flip left to right
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [24]:
y = np.flipud(x) # flip up-down
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [25]:
y = np.roll(x, 8)
print(y)

[[ 8  9 10 11]
 [12 13 14 15]
 [ 0  1  2  3]
 [ 4  5  6  7]]


In [27]:
y = np.rot90(x) # rotated entire matrix anti-clockwise by 90 degrees
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 3  7 11 15]
 [ 2  6 10 14]
 [ 1  5  9 13]
 [ 0  4  8 12]]


# Bitwise operations

In [29]:
x = np.array([0, 1, 0, 1], np.uint8)
y = np.array([0, 0, 1, 1], np.uint8)
print(np.bitwise_and(x, y))
print(np.bitwise_or(x, y))
print(np.bitwise_xor(x, y))

# Since unsigned integer of 8 bits is used,
# binary representation of 0 = 00000000 and hence 255 = 11111111
# binary representation of 1 = 00000001 and hence 254 = 11111110
print(np.bitwise_not(x)) 

[0 0 0 1]
[0 1 1 1]
[0 1 1 0]
[255 254 255 254]


# Statistical functions

In [39]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [36]:
print(np.median(a))
print(np.average(a))
print(np.mean(a))
print(np.std(a))
print(np.var(a))

4.5
4.5
4.5
2.87228132327
8.25


In [37]:
a = np.random.randint(low = 0, high = 10, size = 10)
print(np.median(a))
print(np.average(a))
print(np.mean(a))
print(np.std(a))
print(np.var(a))

3.5
3.9
3.9
3.3
10.89


In [40]:
print(np.histogram(a))

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64), array([ 0. ,  0.9,  1.8,  2.7,  3.6,  4.5,  5.4,  6.3,  7.2,  8.1,  9. ]))
